openapi: 3.0.0
info:
  title: qualitythought_reception_service
  version: '1.0'
servers:
  - url: 'https://qualitythought.in/reciption'
paths:
  /enquiry:
    post:
      summary: ''
      operationId: post-enquiry
      responses:
        '201':
          description: Created
          headers: {}
        '401':
          description: Unauthorized
      description: This endpoint will create the post request for enquirey
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enquiry'
    get:
      summary: ''
      operationId: get-enquiry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/enquiry'
      parameters:
        - schema:
            type: string
            format: date
          in: query
          name: start_date
        - schema:
            type: string
            format: date
          in: query
          name: end_data
        - schema:
            type: string
          in: query
          name: course
components:
  schemas:
    enquiry:
      title: enquiry
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 256
        email:
          type: string
          format: email
          minLength: 5
          maxLength: 256
        mobileNumber:
          type: string
        visitedDateTime:
          type: string
          format: date-time
        courses:
          type: array
          minItems: 1
          maxItems: 5
          items: {}
      x-examples:
        example-1:
          name: khaja
          email: qtkhajacloud@gmail.com
          mobileNumber: '999999999'
          visitedDateTime: '2019-08-24T14:15:22Z'
          courses:
            - Full Stack Python
            - Micro Frontedns
